Areas/Admin/Controllers/TourAjaxController.cs
using ginko_webapp.Areas.Admin.Models.APIResultModels;
using ginko_webapp.Areas.Admin.Models.ObjectModels;
using ginko_webapp.Helper;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ginko_webapp.Areas.Admin.Controllers
{
    public class TourAjaxController : Controller
    {
        private APIConnector connector = new APIConnector();

        public ActionResult GetTours()
        {
            JsonResult result = new JsonResult();
            try
            {
                // server side params
                int start = Convert.ToInt32(Request["start"]);
                int length = Convert.ToInt32(Request["length"]);
                string draw = Request.Form.GetValues("draw")[0];
                string searchValue = Request.Form.GetValues("search[value]")[0];
                string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
                string sortDirection = Request["order[0][dir]"];
                int totalRecords = 0;
                int page = start / length + 1;
                int tourInfoId = Convert.ToInt32(Request["tourInfoId"]);

                // call api to get data
                string token = Session["token"].ToString();
                var client = connector.Initial();
                client.Timeout = -1;
                var request = new RestRequest("admin/tour-infos/" + tourInfoId + "/tours", Method.GET);
                request.AddHeader("Authorization", "Bearer " + token);
                request.AddParameter("page", page);
                request.AddParameter("pageSize", length);
                request.AddParameter("id", tourInfoId);

                IRestResponse response = client.Execute(request);

                // handle result

                if (response.IsSuccessful)
                {
                    var settings = new JsonSerializerSettings
                    {
                        NullValueHandling = NullValueHandling.Ignore,
                        MissingMemberHandling = MissingMemberHandling.Ignore
                    };
                    TourApiResultModel content = JsonConvert.DeserializeObject<TourApiResultModel>(response.Content, settings);
                    List<TourModel> tours = new List<TourModel>();
                    tours.AddRange(content.Data);
                    totalRecords = content.Pagination.TotalElement;
                    int recFilter = totalRecords;

                    // handle search
                    if (!string.IsNullOrEmpty(searchValue) && !string.IsNullOrWhiteSpace(searchValue))
                    {
                        tours = tours.Where(
                            p => p.Name.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.StartDay.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.EndDay.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.TotalDay.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.TotalNight.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.Price.ToString().ToLower().Contains(searchValue.ToLower())
                            ).ToList();

                        totalRecords = tours.Count;
                        recFilter = tours.Count;
                    }

                    // handle sort by column
                    if (sortColumnName == "Name")
                    {
                        tours = (sortDirection == "asc") ? tours.OrderBy(t => t.Name).ToList() : tours.OrderByDescending(t => t.Name).ToList();
                    }
                    else if (sortColumnName == "StartDay")
                    {
                        tours = (sortDirection == "asc") ? tours.OrderBy(t => t.StartDay).ToList() : tours.OrderByDescending(t => t.StartDay).ToList();
                    }
                    else if (sortColumnName == "EndDay")
                    {
                        tours = (sortDirection == "asc") ? tours.OrderBy(t => t.EndDay).ToList() : tours.OrderByDescending(t => t.EndDay).ToList();
                    }
                    else if (sortColumnName == "TotalDay")
                    {
                        tours = (sortDirection == "asc") ? tours.OrderBy(t => t.TotalDay).ToList() : tours.OrderByDescending(t => t.TotalDay).ToList();
                    }
                    else if (sortColumnName == "TotalNight")
                    {
                        tours = (sortDirection == "asc") ? tours.OrderBy(t => t.TotalNight).ToList() : tours.OrderByDescending(t => t.TotalNight).ToList();
                    }
                    else if (sortColumnName == "Price")
                    {
                        tours = (sortDirection == "asc") ? tours.OrderBy(t => t.Price).ToList() : tours.OrderByDescending(t => t.Price).ToList();
                    }

                    result = Json(new
                    {
                        draw = Convert.ToInt32(draw),
                        recordsTotal = totalRecords,
                        recordsFiltered = totalRecords,
                        data = tours
                    }, JsonRequestBehavior.AllowGet); ;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return result;
        }
    }
}

Areas/Admin/Controllers/TourInfoAjaxController.cs
using ginko_webapp.Areas.Admin.Models.APIResultModels;
using ginko_webapp.Areas.Admin.Models.ObjectModels;
using ginko_webapp.Helper;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace ginko_webapp.Areas.Admin.Controllers
{
    public class TourInfoAjaxController : Controller
    {
        private APIConnector connector = new APIConnector();

        public ActionResult GetTourInfos()
        {
            JsonResult result = new JsonResult();
            try
            {
                // server side params
                int start = Convert.ToInt32(Request["start"]);
                int length = Convert.ToInt32(Request["length"]);
                string draw = Request.Form.GetValues("draw")[0];
                string searchValue = Request.Form.GetValues("search[value]")[0];
                string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
                string sortDirection = Request["order[0][dir]"];
                int totalRecords = 0;
                int page = start / length + 1;

                // call api to get data
                string token = Session["token"].ToString();
                var client = connector.Initial();
                client.Timeout = -1;
                var request = new RestRequest("admin/tour-infos", Method.GET);
                request.AddHeader("Authorization", "Bearer " + token);
                request.AddParameter("page", page);
                request.AddParameter("pageSize", length);

                IRestResponse response = client.Execute(request);

                // handle result

                if (response.IsSuccessful)
                {
                    var settings = new JsonSerializerSettings { 
                        NullValueHandling = NullValueHandling.Ignore,
                        MissingMemberHandling = MissingMemberHandling.Ignore
                    };
                    TourInfoApiResultModel content = JsonConvert.DeserializeObject<TourInfoApiResultModel>(response.Content, settings);
                    List<TourInfoModel> tourInfos = new List<TourInfoModel>();
                    tourInfos.AddRange(content.Data);
                    totalRecords = content.Pagination.TotalElement;
                    int recFilter = totalRecords;

                    // handle search
                    if (!string.IsNullOrEmpty(searchValue) && !string.IsNullOrWhiteSpace(searchValue))
                    {
                        tourInfos = tourInfos.Where(
                            p => p.Name.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.Rating.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.StartPlace.Name.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.DestinatePlace.Name.ToString().ToLower().Contains(searchValue.ToLower())
                            ).ToList();

                        totalRecords = tourInfos.Count;
                        recFilter = tourInfos.Count;
                    }

                    // handle sort by column
                    if (sortColumnName == "Name")
                    {
                        tourInfos = (sortDirection == "asc") ? tourInfos.OrderBy(t => t.Name).ToList() : tourInfos.OrderByDescending(t => t.Name).ToList();
                    }
                    else if (sortColumnName == "Rating")
                    {
                        tourInfos = (sortDirection == "asc") ? tourInfos.OrderBy(t => t.Rating).ToList() : tourInfos.OrderByDescending(t => t.Rating).ToList();
                    }
                    else if (sortColumnName == "StartPlace")
                    {
                        tourInfos = (sortDirection == "asc") ? tourInfos.OrderBy(t => t.StartPlace.Name).ToList() : tourInfos.OrderByDescending(t => t.StartPlace.Name).ToList();
                    }
                    else if (sortColumnName == "DestinatePlace")
                    {
                        tourInfos = (sortDirection == "asc") ? tourInfos.OrderBy(t => t.DestinatePlace.Name).ToList() : tourInfos.OrderByDescending(t => t.DestinatePlace.Name).ToList();
                    }

                    result = Json(new
                    {
                        draw = Convert.ToInt32(draw),
                        recordsTotal = totalRecords,
                        recordsFiltered = totalRecords,
                        data = tourInfos
                    }, JsonRequestBehavior.AllowGet); ;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return result;
        }

        public ActionResult DeleteTourInfo(int tourinfoid)
        {
            JsonResult result = new JsonResult();
            try
            {
                // call api to get users data
                string token = Session["token"].ToString();
                var client = connector.Initial();
                client.Timeout = -1;
                var request = new RestRequest("admin/tour-infos/" + tourinfoid, Method.DELETE);
                request.AddHeader("Authorization", "Bearer " + token);

                IRestResponse response = client.Execute(request);

                if (response.IsSuccessful)
                {
                    return Json(new { Status = "success" });
                }
                else
                {
                    return Json(new { Status = "false" });
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return result;
        }
    }
}

Areas/Admin/Views/TourInfo/Create.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    Page.Title = "Tour Info";
}


@section Styles{
}

@model ginko_webapp.Areas.Admin.Models.ViewModels.TourInfoCreateViewModel

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Create New Place</h6>
    </div>
    <div class="card-body">
        <form action="@Url.Action("Create", "TourInfo")" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    @Html.LabelFor(model => model.StartPlace)
                    @Html.DropDownListFor(model => model.StartPlace, (IEnumerable<SelectListItem>)ViewBag.PlacesPicklist, new { @class = "select2 form-control" })
                    @Html.ValidationMessageFor(model => model.StartPlace, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-6">
                    @Html.LabelFor(model => model.DestinatePlace)
                    @Html.DropDownListFor(model => model.DestinatePlace, (IEnumerable<SelectListItem>)ViewBag.PlacesPicklist, new { @class = "select2 form-control" })
                    @Html.ValidationMessageFor(model => model.DestinatePlace, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 form-group">
                    @Html.TextBoxFor(model => model.Images, new { @type = "file", @class = "file", @multiple = "multiple", @data_show_upload = "false", @data_show_caption = "true", @data_msg_placeholder = "Select {files} for upload..." })
                    @Html.ValidationMessageFor(model => model.Images, "", new { @class = "text-danger" })
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

@section Scripts {
   
}

Areas/Admin/Views/TourInfo/Detail.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    Page.Title = "Tour Info";
}


@section Styles{
}

@model ginko_webapp.Areas.Admin.Models.ViewModels.TourInfoEditViewModel

<div class="card shadow mb-4">
    <div class="card-header py-3 clearfix">
        <h6 class="font-weight-bold text-primary float-left">Detail: @Model.Name</h6>
        <a href="@Url.Action("Edit", "TourInfo", new { id = Model.Id})" class="float-right btn bg-primary text-gray-100">Edit</a>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="form-group col-sm-6">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @disabled = "disabled" })
            </div>
            <div class="form-group col-sm-6">
                @Html.LabelFor(model => model.CreateBy)
                @Html.TextBoxFor(model => model.CreateBy, new { @class = "form-control", @disabled = "disabled" })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-sm-6">
                @Html.LabelFor(model => model.StartPlace)
                @Html.DropDownListFor(model => model.StartPlace, (IEnumerable<SelectListItem>)ViewBag.PlacesPicklist, new { @class = "select2 form-control", @disabled = "disabled" })
            </div>
            <div class="form-group col-sm-6">
                @Html.LabelFor(model => model.DestinatePlace)
                @Html.DropDownListFor(model => model.DestinatePlace, (IEnumerable<SelectListItem>)ViewBag.PlacesPicklist, new { @class = "select2 form-control", @disabled = "disabled" })
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 form-group">
                @Html.TextBoxFor(model => model.FileImages, new { @type = "file", @id = "imgFile", @multiple = "multiple", @data_show_upload = "false", @data_show_caption = "true", @data_msg_placeholder = "Select {files} for upload...", @disabled = "disabled" })
                @Html.ValidationMessageFor(model => model.FileImages, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3 clearfix">
        <h6 class="font-weight-bold text-primary float-left">Tours List</h6>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <input type="hidden" name="deleteTourController" value="@Url.Action("DeleteTour", "TourAjax")" />
            <input type="hidden" name="getToursController" value="@Url.Action("GetTours", "TourAjax")" />
            <input type="hidden" name="tourInfoId" value="@Model.Id" />
            <table class="table table-bordered datatable" id="toursDataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th name="Name">Name</th>
                        <th name="StartDay">StartDay</th>
                        <th name="EndDay">EndDay</th>
                        <th name="TotalDay">TotalDay</th>
                        <th name="TotalNight">TotalNight</th>
                        <th name="Price">Price</th>
                        <th name="Edit"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Delete User Modal-->
<div class="modal fade" id="deleteTourModal" tabindex="-1" role="dialog" aria-labelledby="deleteTourModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteTourModalLabel">Confirm to delete</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <button class="btn btn-primary" placeId="">Confirm</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Areas/Admin/Resources/ToursListView.js"></script>
    <script>
         $("#imgFile").fileinput({
            "theme": "fas",
            "initialPreview": JSON.parse('@Html.Raw(Json.Encode(Model.Images))'),
            "initialPreviewAsData": true,
         });
    </script>
}

Areas/Admin/Views/TourInfo/Edit.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    Page.Title = "Tour Info";
}


@section Styles{
}

@model ginko_webapp.Areas.Admin.Models.ViewModels.TourInfoEditViewModel

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Edit Tour Info</h6>
    </div>
    <div class="card-body">
        <form action="@Url.Action("Edit", "TourInfo")" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="row">
                <div class="form-group col-sm-6">
                    @Html.LabelFor(model => model.Name)
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-6">
                    @Html.LabelFor(model => model.CreateBy)
                    @Html.TextBoxFor(model => model.CreateBy, new { @class = "form-control", @disabled = "disabled"})
                    @Html.ValidationMessageFor(model => model.CreateBy, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="form-group col-sm-6">
                    @Html.LabelFor(model => model.StartPlace)
                    @Html.DropDownListFor(model => model.StartPlace, (IEnumerable<SelectListItem>)ViewBag.PlacesPicklist, new { @class = "select2 form-control" })
                    @Html.ValidationMessageFor(model => model.StartPlace, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-sm-6">
                    @Html.LabelFor(model => model.DestinatePlace)
                    @Html.DropDownListFor(model => model.DestinatePlace, (IEnumerable<SelectListItem>)ViewBag.PlacesPicklist, new { @class = "select2 form-control" })
                    @Html.ValidationMessageFor(model => model.DestinatePlace, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 form-group">
                    @Html.TextBoxFor(model => model.FileImages, new { @type = "file", @id = "imgFile", @multiple = "multiple", @data_show_upload = "false", @data_show_caption = "true", @data_msg_placeholder = "Select {files} for upload..." })
                    @Html.ValidationMessageFor(model => model.FileImages, "", new { @class = "text-danger" })
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>

@section Scripts {
<script>
    $("#imgFile").fileinput({
        "theme": "fas",
        "initialPreview": JSON.parse('@Html.Raw(Json.Encode(Model.Images))'),
        "initialPreviewAsData": true,
    });
</script>
}

Areas/Admin/Views/TourInfo/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    Page.Title = "Tour Info";
}

<div class="card shadow mb-4">
    <div class="card-header py-3 clearfix">
        <h6 class="font-weight-bold text-primary float-left">Tour info list</h6>
        <a href="@Url.Action("Create", "TourInfo")" class="float-right btn bg-primary text-gray-100">Add new tour info</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <input type="hidden" name="deleteTourInfoController" value="@Url.Action("DeleteTourInfo", "TourInfoAjax")" />
            <input type="hidden" name="getTourInfosController" value="@Url.Action("GetTourInfos", "TourInfoAjax")" />
            <table class="table table-bordered datatable" id="tourInfosDataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th name="Name">Name</th>
                        <th name="Rating">Rating</th>
                        <th name="Start Place">Start Place</th>
                        <th name="End Place">End Place</th>
                        <th name="Edit"></th>
                        <th name="Detail"></th>
                        <th name="Delete"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Delete User Modal-->
<div class="modal fade" id="deleteTourInfoModal" tabindex="-1" role="dialog" aria-labelledby="deleteTourInfoModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteTourInfoModalLabel">Confirm to delete</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <button class="btn btn-primary" placeId="">Confirm</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Areas/Admin/Resources/TourInfoListView.js"></script>
}