Areas/Admin/Controllers/UserAjaxController.cs
using ginko_webapp.Areas.Admin.Models.APIResultModels;
using ginko_webapp.Areas.Admin.Models;
using ginko_webapp.Helper;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using RestSharp;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Http;
using System.Web.Mvc;
using ginko_webapp.Areas.Admin.Models.ObjectModels;

namespace ginko_webapp.Areas.Admin.Controllers
{
    public class UserAjaxController : Controller
    {
        private APIConnector connector = new APIConnector();

        public ActionResult GetUsers()
        {
            JsonResult result = new JsonResult();
            try
            {
                // server side params
                int start = Convert.ToInt32(Request["start"]);
                int length = Convert.ToInt32(Request["length"]);
                string draw = Request.Form.GetValues("draw")[0];
                string searchValue = Request.Form.GetValues("search[value]")[0];
                string sortColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
                string sortDirection = Request["order[0][dir]"];
                int totalRecords = 0;
                int page = start / length + 1;

                // call api to get users data
                string token = Session["token"].ToString();
                var client = connector.Initial();
                client.Timeout = -1;
                var request = new RestRequest("admin/users", Method.GET);
                request.AddHeader("Authorization", "Bearer " + token);
                request.AddParameter("page", page);
                request.AddParameter("pageSize", length);

                IRestResponse response = client.Execute(request);

                // handle result

                if (response.IsSuccessful)
                {
                    UsersApiResultModel content = JsonConvert.DeserializeObject<UsersApiResultModel>(response.Content);
                    List<UserModel> users = new List<UserModel>();
                    users.AddRange(content.Data);
                    totalRecords = content.Pagination.TotalElement;
                    int recFilter = totalRecords;

                    // handle search
                    if (!string.IsNullOrEmpty(searchValue) && !string.IsNullOrWhiteSpace(searchValue))
                    {
                        users = users.Where(
                            p => p.Name.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.Email.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.PhoneNumber.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.Birthday.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.Gender.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.Address.ToString().ToLower().Contains(searchValue.ToLower()) ||
                            p.Role.ToString().ToLower().Contains(searchValue.ToLower())
                            ).ToList();

                        totalRecords = users.Count;
                        recFilter = users.Count;
                    }

                    // handle sort by column
                    if(sortColumnName == "Name")
                    {
                        users = (sortDirection == "asc") ? users.OrderBy(u => u.Name).ToList() : users.OrderByDescending(u => u.Name).ToList();
                    }
                    else if(sortColumnName == "Email")
                    {
                        users = (sortDirection == "asc") ? users.OrderBy(u => u.Email).ToList() : users.OrderByDescending(u => u.Email).ToList();
                    }
                    else if(sortColumnName == "Phone")
                    {
                        users = (sortDirection == "asc") ? users.OrderBy(u => u.PhoneNumber).ToList() : users.OrderByDescending(u => u.PhoneNumber).ToList();
                    }
                    else if(sortColumnName == "Birthday")
                    {
                        users = (sortDirection == "asc") ? users.OrderBy(u => u.Birthday).ToList() : users.OrderByDescending(u => u.Birthday).ToList();
                    }
                    else if(sortColumnName == "Gender")
                    {
                        users = (sortDirection == "asc") ? users.OrderBy(u => u.Gender).ToList() : users.OrderByDescending(u => u.Gender).ToList();
                    }
                    else if(sortColumnName == "Address")
                    {
                        users = (sortDirection == "asc") ? users.OrderBy(u => u.Address).ToList() : users.OrderByDescending(u => u.Address).ToList();
                    }
                    else if(sortColumnName == "Role")
                    {
                        users = (sortDirection == "asc") ? users.OrderBy(u => u.Role).ToList() : users.OrderByDescending(u => u.Role).ToList();
                    }

                    result = Json(new {
                        draw = Convert.ToInt32(draw),
                        recordsTotal = totalRecords,
                        recordsFiltered = totalRecords,
                        data = users
                    }, JsonRequestBehavior.AllowGet);;
                }
            }
            catch(Exception ex)
            {
                Console.WriteLine(ex);
            }
            return result;
        }

        public ActionResult DeleteUser(int userId)
        {
            JsonResult result = new JsonResult();
            try
            {
                // call api to get users data
                string token = Session["token"].ToString();
                var client = connector.Initial();
                client.Timeout = -1;
                var request = new RestRequest("admin/users/" + userId, Method.DELETE);
                request.AddHeader("Authorization", "Bearer " + token);

                IRestResponse response = client.Execute(request);

                if(response.IsSuccessful)
                {
                    return Json(new { Status = "success"});
                }
                else
                {
                    return Json(new { Status = "false" });
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
            return result;
        }
    }

    public class DataTableData
    {
        public int draw { get; set; }
        public int recordsTotal { get; set; }
        public int recordsFiltered { get; set; }
        public List<UserModel> data { get; set; }
    }
};

Areas/Admin/Controllers/UserController.cs
using ginko_webapp.Areas.Admin.Models.APIResultModels;
using ginko_webapp.Areas.Admin.Models.ObjectModels;
using ginko_webapp.Areas.Admin.Models.ViewModels;
using ginko_webapp.Helper;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ginko_webapp.Areas.Admin.Controllers
{
    public class UserController : Controller
    {
        private APIConnector connector = new APIConnector();

        public ActionResult CheckAuthentication(ref string token)
        {
            if(Session["token"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            token = Session["token"].ToString();
            return null;
        }

        public ActionResult Index()
        {
            string token = "";
            CheckAuthentication(ref token);

            return View();
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            if(id == null)
            {
                return RedirectToAction("Index", "User");
            }

            string token = Session["token"].ToString();

            var client = connector.Initial();
            client.Timeout = -1;
            var request = new RestRequest("admin/users/" + id, Method.GET);
            request.AddHeader("Authorization", "Bearer " + token);
            IRestResponse response = client.Execute(request);

            UserModel user = new UserModel();
            UserEditViewModel model;

            if (response.IsSuccessful)
            {
                UsersApiResultModel content = JsonConvert.DeserializeObject<UsersApiResultModel>(response.Content);
                user = content.Data[0];
                model = new UserEditViewModel() { 
                    Name = user.Name,
                    Email = user.Email,
                    PhoneNumber = user.Name,
                    Avatar = user.Avatar,
                    Bio = user.Bio,
                    Slogan = user.Slogan,
                    Job = user.Job,
                    Birthday = user.Birthday,
                    Gender = user.Gender,
                    Address = user.Address,
                    Role = user.Role
                };
                return View(model);
            }
            else
            {
                return RedirectToAction("Index", "User");
            }
        }

        [HttpPost]
        [ActionName("Edit")]
        public ActionResult EditPost(string id, UserEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                if (Session["token"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
                string token = Session["token"].ToString();

                var client = connector.Initial();
                client.Timeout = -1;
                var request = new RestRequest("admin/users/" + id, Method.PUT);
                request.AddHeader("Authorization", "Bearer " + token);
                request.AddHeader("Content-Type", "application/json");
                request.AddJsonBody(new
                {
                    Name = model.Name,
                    Email = model.Email,
                    Password = model.Password,
                    PhoneNumber = model.PhoneNumber,
                    Address = model.Address,
                    Avatar = model.Avatar,
                    Slogan = model.Slogan,
                    Bio = model.Bio,
                    Job = model.Job,
                    Gender = model.Gender,
                    Birthday = model.Birthday,
                    Role = model.Role,
                });

                IRestResponse response = client.Execute(request);
                if (response.IsSuccessful)
                {
                    APIResultModel result = JsonConvert.DeserializeObject<APIResultModel>(response.Content);
                    if (result.ErrorCode != 0)
                    {
                        ViewBag.error = result.Message;
                        return View();
                    }

                    return RedirectToAction("Index", "User");
                }
                else
                {
                    return RedirectToAction("Edit", "User");
                }
            }
            return View();
        }

        [HttpGet]
        public ActionResult Create()
        {
            UserCreateViewModel model = new UserCreateViewModel();
            return View(model);
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult CreatePost(UserCreateViewModel model)
        {
            if(ModelState.IsValid)
            {
                if (Session["token"] == null)
                {
                    return RedirectToAction("Index", "Login");
                }
                string token = Session["token"].ToString();

                var client = connector.Initial();
                client.Timeout = -1;
                var request = new RestRequest("admin/users", Method.POST);
                request.AddHeader("Authorization", "Bearer " + token);
                request.AddHeader("Content-Type", "application/json");
                request.AddJsonBody(new
                {
                    Name = model.Name,
                    Email = model.Email,
                    Password = model.Password,
                    PhoneNumber = model.PhoneNumber,
                    Address = model.Address,
                    Avatar = model.Avatar,
                    Slogan = model.Slogan,
                    Bio = model.Bio,
                    Job = model.Job,
                    Gender = model.Gender,
                    Birthday = model.Birthday,
                    Role = model.Role,
                });

                IRestResponse response = client.Execute(request);
                if (response.IsSuccessful)
                {
                    APIResultModel result = JsonConvert.DeserializeObject<APIResultModel>(response.Content);
                    if (result.ErrorCode != 0)
                    {
                        ViewBag.error = result.Message;
                        return View();
                    }

                    return RedirectToAction("Index", "User");
                }
                else
                {
                    return RedirectToAction("Create", "User");
                }
            }
            return View();
        }
    }
}

Areas/Admin/Views/User/Create.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    Page.Title = "Users";
}


@section Styles{
    @Styles.Render("~/datepicker/css")
    @Styles.Render("~/avtpicker/css")
}

@model ginko_webapp.Areas.Admin.Models.ViewModels.UserCreateViewModel

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Create New User</h6>
    </div>
    <div class="card-body">
        <form action="@Url.Action("Create", "User")" method="post">
            @Html.AntiForgeryToken()
            <div class="form-row">
                <div class="col-md-4 center-content">
                    <div class="avt-wrapper">
                        <div class="circle-avt">
                            <img class="profile-pic" src="~/Areas/Admin/Img/avatar-default.png">
                        </div>
                        <div class="p-image">
                            <i class="fa fa-camera upload-button"></i>
                            <input class="file-upload-avt" type="file" accept="image/*" />
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="form-group col-md-8">
                            @Html.LabelFor(model => model.Email)
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Role)
                            @Html.DropDownListFor(
                                    model => model.Role,
                                    new List<SelectListItem>{
                                        new SelectListItem{ Text="Choose...", Value = "" },
                                        new SelectListItem{ Text="Admin", Value = "admin" },
                                        new SelectListItem{ Text="User", Value = "user" },
                                        new SelectListItem{ Text="Creator", Value = "creator" }
                                    },
                                    new { @class = "form-control", @selected_data = "" }
                                )
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            @Html.LabelFor(model => model.Password)
                            @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-8">
                            @Html.LabelFor(model => model.Name)
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Gender)
                            @Html.DropDownListFor(
                                    model => model.Gender,
                                    new List<SelectListItem>{
                                        new SelectListItem{ Text="Choose...", Value = "" },
                                        new SelectListItem{ Text="Male", Value = "male" },
                                        new SelectListItem{ Text="Female", Value = "female" },
                                        new SelectListItem{ Text="Orther", Value = "orther" }
                                    },
                                    new { @class = "form-control", @selected_data = "" }
                                )
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.PhoneNumber)
                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Birthday)
                    @Html.TextBoxFor(model => model.Birthday, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger", data_provide = "datepicker" })
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Job)
                    @Html.TextBoxFor(model => model.Job, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Job, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Address)
                @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Slogan)
                @Html.TextAreaFor(model => model.Slogan, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Slogan, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Bio)
                @Html.TextAreaFor(model => model.Bio, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/datepicker/js")
    @Scripts.Render("~/avtpicker/js")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[name="Birthday"]').datepicker();
        });
    </script>
}

Areas/Admin/Views/User/Edit.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    Page.Title = "Users";
}

@model ginko_webapp.Areas.Admin.Models.ViewModels.UserEditViewModel


@section Styles{
    @Styles.Render("~/datepicker/css")
    @Styles.Render("~/avtpicker/css")
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Editing:&nbsp;</h6>
    </div>
    <div class="card-body">
        <form action="@Url.Action("Edit", "User")" method="post" enctype="multipart/form-data">
            @Html.AntiForgeryToken()
            <div class="form-row">
                <div class="col-md-4 center-content">
                    <div class="avt-wrapper">
                        <div class="circle-avt">
                            @if (@Model.Avatar != "")
                            {
                                <img class="profile-pic" src="@Model.Avatar">
                            }
                            else
                            {
                                <img class="profile-pic" src="~/Areas/Admin/Img/avatar-default.png">
                            }
                        </div>
                        <div class="p-image">
                            <i class="fa fa-camera upload-button"></i>
                            <input class="file-upload-avt" type="file" accept="image/*"/>
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="row">
                        <div class="form-group col-md-8">
                            @Html.LabelFor(model => model.Email)
                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Role)
                            @Html.DropDownListFor(
                                    model => model.Role,
                                    new List<SelectListItem>{
                                        new SelectListItem{ Text="Choose...", Value = "" },
                                        new SelectListItem{ Text="Admin", Value = "admin" },
                                        new SelectListItem{ Text="User", Value = "user" },
                                        new SelectListItem{ Text="Creator", Value = "creator" }
                                    },
                                    new { @class = "form-control", @selected_data = "" }
                                )
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            @Html.LabelFor(model => model.Password)
                            @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-md-8">
                            @Html.LabelFor(model => model.Name)
                            @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-md-4">
                            @Html.LabelFor(model => model.Gender)
                            @Html.DropDownListFor(
                                    model => model.Gender,
                                    new List<SelectListItem>{
                                        new SelectListItem{ Text="Choose...", Value = "" },
                                        new SelectListItem{ Text="Male", Value = "male" },
                                        new SelectListItem{ Text="Female", Value = "female" },
                                        new SelectListItem{ Text="Orther", Value = "orther" }
                                    },
                                    new { @class = "form-control", @selected_data = "" }
                                )
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.PhoneNumber)
                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Birthday)
                    @Html.TextBoxFor(model => model.Birthday, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Birthday, "", new { @class = "text-danger", @data_provide = "datepicker" })
                </div>
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.Job)
                    @Html.TextBoxFor(model => model.Job, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Job, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Address)
                @Html.TextBoxFor(model => model.Address, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Slogan)
                @Html.TextAreaFor(model => model.Slogan, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Slogan, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Bio)
                @Html.TextAreaFor(model => model.Bio, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Bio, "", new { @class = "text-danger" })
            </div>

            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>



@section Scripts {
    @Scripts.Render("~/datepicker/js")
    @Scripts.Render("~/avtpicker/js")

    <script type="text/javascript">
        $(document).ready(function () {
            $('input[name="Birthday"]').datepicker();
        });
    </script>
}

Areas/Admin/Views/User/Index.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    Page.Title = "Users";
}

<div class="card shadow mb-4">
    <div class="card-header py-3 clearfix">
        <h6 class="font-weight-bold text-primary float-left">Users list</h6>
        <a href="@Url.Action("Create", "User")" class="float-right btn bg-primary text-gray-100">Add new users</a>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <input type="hidden" name="deleteUserController" value="@Url.Action("DeleteUser", "UserAjax")" />
            <input type="hidden" name="getUsersController" value="@Url.Action("GetUsers", "UserAjax")" />
            <table class="table table-bordered datatable" id="usersDataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th name="Name">Name</th>
                        <th name="Email">Email</th>
                        <th name="Phone">Phone</th>
                        <th name="Birthday">Birthday</th>
                        <th name="Gender">Gender</th>
                        <th name="Address">Address</th>
                        <th name="Role">Role</th>
                        <th name="Edit"></th>
                        <th name="Delete"></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Delete User Modal-->
<div class="modal fade" id="deleteUserModal" tabindex="-1" role="dialog" aria-labelledby="deleteUserModal" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteUserModalLabel">Confirm to delete</h5>
                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                <button class="btn btn-primary" userId="">Confirm</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript" src="~/Areas/Admin/Resources/UsersListView.js"></script>
}